pipeline {
agent any
tools {
maven 'MAVEN'
}
stages {
stage ('BUILD') {
steps {
checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: '3b78e4e7-2dc6-47bc-b45b-908c3b7cf3d2', url: 'https://github.com/sachinhs9214/jenkins-docker-pipeline.git']]])
sh "mvn clean package"
}


}

stage ('docker-image') {
steps {
script {
sh 'docker build -t sachinhs9214/my_ubuntu:java .'
}

}


}

stage ('push-docker-image') {
steps {
script {
withCredentials([string(credentialsId: 'sachinhs9214@gmail.com', variable: 'dockerhubpwd')]) {
sh 'docker login -u sachinhs9214 -p ${dockerhubpwd}'   
}
sh 'docker push sachinhs9214/my_ubuntu:java'

}
}
}


}
}
