pipeline {
agent none 
tools {
maven 'MAVEN'
}
stages {
stage ('Git-Clone') {
 agent {
                label "master"
            }
steps {
checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: '1c71be00-fe12-405e-9f8c-a532f4b2affd', url: 'https://github.com/sachinhs9214/devops-june-2022.git']]])
sh 'pwd'
}


}

stage ('Build-Deploy') {
 agent {
                label "Docker-slave"
            }
steps {
script {
sh '''
docker build -t sachinhs9214/my_ubuntu:maven .
docker run -it --rm -d -p 8080:8080 --name calc sachinhs9214/my_ubuntu:maven
'''
}

}


}

stage ('push-docker-image') {
 agent {
                label "Docker-slave"
            }
steps {
script {
withCredentials([string(credentialsId: 'dockerhubpwd', variable: 'dockerhubpwd')]) {
sh 'docker login -u sachinhs9214 -p ${dockerhubpwd}'
}

sh 'docker push sachinhs9214/my_ubuntu:maven'
}
}
}



}
}
